# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

LINKER_VARIANT = 1024

include $(CPUS)/stm32l496/Makefile.include
