# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

SUPPORTED_BOARDS = \
	rgbduino \
	nucleo_wb55_dongle \
	ublox_nora_b1_eval
BOARD ?= ublox_nora_b1_eval

include ../../mcud.mk
