# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

SUPPORTED_BOARDS = \
	fri3d-badge-2020-00 \
	ublox_nora_b1_eval
BOARD ?= ublox_nora_b1_eval

include ../../mcud.mk
